# Generated by Django 3.2.9 on 2022-10-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=19),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
